### ISSUE TITLE
Mirage as 1st pick in round re-shuffles hand

### ISSUE THREAD

**Issue by crmirand** [KevinVillela/lovecraft#14]
While playing a game in the room 6otr we encountered a bug where our hands were reshuffled after 'mirage' was the first card picked in round 2.
Everyone's hands were re-shuffled and the round counter advanced to round 3

**Comment by crmirand** [comment]
Believe that the issue occurs [here](https://github.com/KevinVillela/lovecraft/blob/ed754e843534a78f8ad4172de2206fcb02cf877a/game/reducers/card_reducers.ts#L209) when checking whether the visible cards is evenly divisible by the number of players.
In this instance, we are at the start of the round so there are no additional cards visible. After 'mirage' is played, the mirage card replaces a card which was previously visible, so the number of visible cards ends up being evenly divisible by the number of players.
maybe something like below would fix the bug here?
`
if (game.visibleCards.length !== game.playerList.length * game.round) {
    return false;
  }
`

**Comment by KevinVillela** [comment]
Thanks for filing! Will take a look now...

**Comment by KevinVillela** [comment]
Thanks for filing, should be fixed in prod now :)
